# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.101'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    dotnet test UnitTests/UnitTests.csproj /p:CollectCoverage=true /maxcpucount:8 /p:CoverletOutput="../coverage" /p:CoverletOutputFormat=\"json,opencover\"
  displayName: 'Run a multi-line script'

- script: |
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Upload to codecov.io'
